file_ids:
- secrets/secret0.something
- secrets/secret1.something
- secrets/secret2.something
- secrets/secret3.something
- secrets/secret4.something
- secrets/secret5.something
- secrets/secret6.something
- secrets/subsecrets/secret0.something
- secrets/subsecrets/secret1.something
- secrets/subsecrets/secret2.something
- secrets/subsecrets/secret3.something
- secrets/subsecrets/secret4.something
- secrets/subsecrets/secret5.something
- secrets/subsecrets/secret6.something
- secrets/subsecrets/subsubsecrets/secret0.something
- secrets/subsecrets/subsubsecrets/secret1.something
- secrets/subsecrets/subsubsecrets/secret2.something
- secrets/subsecrets/subsubsecrets/secret3.something
- secrets/subsecrets/subsubsecrets/secret4.something
- secrets/subsecrets/subsubsecrets/secret5.something
- secrets/subsecrets/subsubsecrets/secret6.something
- secrets/subsecrets2/secret0.something
- secrets/subsecrets2/secret1.something
- secrets/subsecrets2/secret2.something
- secrets/subsecrets2/secret3.something
- secrets/subsecrets2/secret4.something
- secrets/subsecrets2/secret5.something
- secrets/subsecrets2/secret6.something
version: "1"
